#ifndef FG_TYPE_GL_VERSION_H
#define FG_TYPE_GL_VERSION_H

typedef enum FgGLVersion
{
    FG_GL_VERSION_INVALID = 0x0,

#define GL_VERSION_TYPE_POS 16
#define GL_VERSION_TYPE_BITS 16
#define GL_VERSION_TYPE ( 1 << GL_VERSION_TYPE_POS )

#define GL_VERSION_MAJOR_POS 8
#define GL_VERSION_MAJOR_BITS 8
#define GL_VERSION_MAJOR ( 1 << GL_VERSION_MAJOR_POS )

    FG_GL_VERSION_TYPE_MASK = ( ( 1 << GL_VERSION_TYPE_BITS ) - 1 ) << GL_VERSION_TYPE_POS,
    FG_GL_VERSION_MAJOR_MASK = ( ( 1 << GL_VERSION_MAJOR_BITS ) - 1 ) << GL_VERSION_MAJOR_POS,

    FG_GL_VERSION_BASE = GL_VERSION_TYPE,
    FG_GL_VERSION_1_0 = FG_GL_VERSION_BASE + GL_VERSION_MAJOR,
    FG_GL_VERSION_1_1,
    FG_GL_VERSION_1_2,
    FG_GL_VERSION_1_3,
    FG_GL_VERSION_1_4,
    FG_GL_VERSION_1_5,
    FG_GL_VERSION_2_0 = FG_GL_VERSION_1_0 + GL_VERSION_MAJOR,
    FG_GL_VERSION_2_1,
    FG_GL_VERSION_3_0 = FG_GL_VERSION_2_0 + GL_VERSION_MAJOR,
    FG_GL_VERSION_3_1,
    FG_GL_VERSION_3_2,
    FG_GL_VERSION_3_3,
    FG_GL_VERSION_4_0 = FG_GL_VERSION_3_0 + GL_VERSION_MAJOR,
    FG_GL_VERSION_4_1,
    FG_GL_VERSION_4_2,
    FG_GL_VERSION_4_3,
    FG_GL_VERSION_4_4,

    FG_GLES_VERSION_BASE = FG_GL_VERSION_BASE + GL_VERSION_TYPE,
    FG_GLES_VERSION_1_0 = FG_GLES_VERSION_BASE + GL_VERSION_MAJOR,
    FG_GLES_VERSION_1_1,
    FG_GLES_VERSION_2_0 = FG_GLES_VERSION_1_0 + GL_VERSION_MAJOR,
    FG_GLES_VERSION_3_0 = FG_GLES_VERSION_2_0 + GL_VERSION_MAJOR,

#undef  GL_VERSION_MAJOR
#undef  GL_VERSION_MAJOR_BITS
#undef  GL_VERSION_MAJOR_POS

#undef  GL_VERSION_TYPE
#undef  GL_VERSION_TYPE_BITS
#undef  GL_VERSION_TYPE_POS
} FgGLVersion;

#endif  // FG_TYPE_GL_VERSION_H
