#ifndef FG_GL_VERSION_H
#define FG_GL_VERSION_H

typedef enum FgGLVersion
{
    FG_GL_VERSION_INVALID = 0x0,

    _FG_GL_VERSION_SUBSET = 0x10000,
    _FG_GL_VERSION_MAJOR = 0x100,

    FG_GL_VERSION = _FG_GL_VERSION_SUBSET,
    FG_GL_VERSION_1_0 = FG_GL_VERSION + _FG_GL_VERSION_MAJOR,
    FG_GL_VERSION_1_1,
    FG_GL_VERSION_1_2,
    FG_GL_VERSION_1_3,
    FG_GL_VERSION_1_4,
    FG_GL_VERSION_1_5,
    FG_GL_VERSION_2_0 = FG_GL_VERSION_1_0 + _FG_GL_VERSION_MAJOR,
    FG_GL_VERSION_2_1,
    FG_GL_VERSION_3_0 = FG_GL_VERSION_2_0 + _FG_GL_VERSION_MAJOR,
    FG_GL_VERSION_3_1,
    FG_GL_VERSION_3_2,
    FG_GL_VERSION_3_3,
    FG_GL_VERSION_4_0 = FG_GL_VERSION_3_0 + _FG_GL_VERSION_MAJOR,
    FG_GL_VERSION_4_1,
    FG_GL_VERSION_4_2,
    FG_GL_VERSION_4_3,

    FG_GLES_VERSION = FG_GL_VERSION + _FG_GL_VERSION_SUBSET,
    FG_GLES_VERSION_1_0 = FG_GLES_VERSION + _FG_GL_VERSION_MAJOR,
    FG_GLES_VERSION_1_1,
    FG_GLES_VERSION_2_0 = FG_GLES_VERSION_1_0 + _FG_GL_VERSION_MAJOR,
    FG_GLES_VERSION_3_0 = FG_GLES_VERSION_2_0 + _FG_GL_VERSION_MAJOR,
} FgGLVersion;

#endif  // FG_GL_VERSION_H
